### ISSUE TITLE
Image Embedding: add support for reading images from urls 

### ISSUE THREAD

**Issue by inejc** [biolab/orange3-imageanalytics#10]
This is the only missing functionality that wasn't reimplemented in https://github.com/biolab/orange3-imageanalytics/pull/6 (Image Embedding rewrite).

**Comment by inejc** [comment]
Can someone with sufficient permissions assign this issue to me please? @BlazZupan

**Comment by brylie** [comment]
@earthling2304 thanks for your interest in contributing! Is there anything we can do to help you get started on this task?

**Comment by inejc** [comment]
The image loading part is currently in the ImageEmbedder class (see the `_load_image_or_none` method). The implementation should include checking whether the path is a "local" path or a "network" path (probably with a regex). [This](http://pillow.readthedocs.io/en/3.1.x/releasenotes/2.8.0.html) should help with opening the images. Let us know if you need any help.

**Comment by earthling2304** [comment]
Shall I use urllib to parse the url and check the scheme attribute?

**Comment by inejc** [comment]
Sure, you could use `urllib.parse` instead of writing an explicit regex.

By the way, to make a contribution you should fork the repository to your own account, make a new branch for your changes and then open the pull request to the original repository from that branch. My apologies if you already know all of that, I've just noticed that you haven't forked the project yet :).

**Comment by inejc** [comment]
Hey. How is this going? Do you need any help? In case you have changed your mind, please let me know so I can implement this. Thank you.

**Comment by earthling2304** [comment]
Hey, I am not sure about how I can test if my changes are working. Can you help me with that? Thank you.

**Comment by earthling2304** [comment]
Since I am new to this, I was trying to figure out things on my own. I am sorry about not asking earlier!

**Comment by brylie** [comment]
@earthling2304 do you have your work in progress on Github? I can check out the code and try to run it locally.

**Comment by earthling2304** [comment]
Yes, can you please check if it's working?

**Comment by brylie** [comment]
Sure, **where** can I check?

**Comment by brylie** [comment]
Go ahead and open a pull request against this repository. That way we can review your work in progress, and comment directly about the proposed changes. Let me know when the PR is open, and I will continue investigating.

**Comment by ajdapretnar** [comment]
Fixed via #31.
