### ISSUE TITLE
Slow Image Viewer

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-imageanalytics#110]
##### Orange version
3.4.2

##### Expected behavior
Optimize image loading or memory resources

##### Actual behavior
I have a dataset of ~5000 images. It's not such a large number, but after connecting data to it, it turns really slow.

Also, if I remove the image viewer it seems like memory used for images isn't get released.

**Comment by PrimozGodec** [comment]
@ales-erjavec do you have any idea how to make Image Viewer faster?

**Comment by PrimozGodec** [comment]
Closing via #147
