### ISSUE TITLE
[enhancement request] Labels on Image grid

### ISSUE THREAD

**Issue by salvatoreloguercio** [biolab/orange3-imageanalytics#113]
Hello! I was wondering if labels could be visualized on images in the image grid tool in Image Analytics? See pic attached.

I know, this feature might be not terribly useful for images in general, hence unlikely to be deployed in Orange. How hard it would be to modify image_grid.py in order to display such image names? Any pointers would be useful.

I am asking because my fellow biologists would like to see gene names on the corresponding images on imageGrid, but labeling them manually is quite impractical for 500+ genes.

##### Image Analytics version
0.2.1
##### Orange version
3.15.0

<img width="239" alt="screen shot 2018-09-07 at 3 59 45 pm" src="https://user-images.githubusercontent.com/8292856/45246746-ce051900-b2b7-11e8-9b93-dbf1048fe47b.png">

**Comment by salvatoreloguercio** [comment]
Bump - any feedback on this?

**Comment by ajdapretnar** [comment]
Perhaps something @janhartman or @PrimozGodec could implement? It should probably work with 'Label only selected images', like in Scatter Plot. Or would tooltips be a better solution, @salvatoreloguercio? Do you need this for report or for inspection?

**Comment by salvatoreloguercio** [comment]
@ajdapretnar sorry I missed this.. Yes something along the lines of 'Label selected images' like in Scatterplot would be useful. This would be for report more than inspection (if you hover on the images you already see a tooltip showing the image path). The use case is to generate labeled figures for grants/publications, so solid labels would be nice.

**Comment by PrimozGodec** [comment]
It is now implemented in #136
