### ISSUE TITLE
Save Images

### ISSUE THREAD

**Issue by BlazZupan** [biolab/orange3-imageanalytics#132]
It would be great if we could have a widget for saving images. The widget would take Data Table (Data) on input and would create a directory and possibly subdirectories for classes to save the images. 

The widget would behave like Save widget, but would also need to include the "Scale images" option (default:true) to scale images to reduce the size and match the format for deep learning-based embedders. The option would also offer the choice of the format (Format:), where the default is "299x299 (Inception v3)".

An example script for saving the images that I am now using in Python Script widget for this task is at https://github.com/BlazZupan/baylor-snippets/blob/master/code/save-images.py.

**Comment by PrimozGodec** [comment]
Closing via #133
