### ISSUE TITLE
Hyper alternative

### ISSUE THREAD

**Issue by matjazp** [biolab/orange3-imageanalytics#146]
Just stumbled on this interesting stuff: https://github.com/encode/httpx. We could test it as a replacement for now unmaintained Hyper...

Thoughts?

**Comment by PrimozGodec** [comment]
I think using this library is a good idea. It looks well maintained. Also, based on documentation it has all the features that we need. 

We can use parallel requst, similarly than it is done with Hyper now:

    with httpx.parallel() as parallel:
        for counter in range(1, 10):
            parallel.get(f'https://example.com/{counter}')
        while parallel.has_pending_responses:
            r = parallel.next_response()

It also offers an Async client if we would like to switch to.
