### ISSUE TITLE
Import Images: widget should not load any images on opening the saved workflow if they are not provided

### ISSUE THREAD

**Issue by PrimozGodec** [biolab/orange3-imageanalytics#156]
##### Expected behavior
When opening the workflow from the file Import Images widget should load images if they are available or it should not load any image when they do not come together with the workflow.

##### Actual behavior
Widgets loads images when they are available but it loads different images from user's history when images from the workflow do not exist.

##### Steps to reproduce the behavior
See https://github.com/biolab/orange3/issues/4108

**Comment by PrimozGodec** [comment]
@ajdapretnar I actually cannot reproduce that issue. In my case when I open an empty workflow a use Import Images it opens the last used directory (which is correct), but when I open the workflow from https://github.com/biolab/orange3/issues/4108 it does not load any images (which is correct too).

**Comment by ajdapretnar** [comment]
You are right. I don't know what I saw yesterday. It looked like Import Images opened the previous folder instead. Closing.
