### ISSUE TITLE
Mentorship available for new developer interested in image mining?

### ISSUE THREAD

**Issue by brylie** [biolab/orange3-imageanalytics#17]
There is a new developer on the [Orange3 Gitter channel](https://gitter.im/biolab/orange3), named @ava23, who is interested in image mining (for astronomical research). Are there any 'low hanging fruit' type tasks that could be used as an entry point into ImageAnalytics development? Would anyone here be available as a mentor to help developers contribute?

**Comment by ajdapretnar** [comment]
Perhaps @inejc can find some easy tasks for prospective students?

**Comment by earthling2304** [comment]
Hello, I am Vasudha, and I was interested in image mining for astronomical research. I would love to get started right away on any task. Thank you!

**Comment by inejc** [comment]
Hi Vasudha. You can take a look at https://github.com/biolab/orange3-imageanalytics/issues/10. The image embedding widget can only load local images at the moment, but should be able to also load them from URLs. If you are interested in implementing this I can assign the issue to you and give some directions.

**Comment by earthling2304** [comment]
Hi @inejc , yes I'll work on implementing this.

**Comment by PrimozGodec** [comment]
I think it can be closed due to inactivity.
