### ISSUE TITLE
Image Embedding - Not visible

### ISSUE THREAD

**Issue by raybg** [biolab/orange3-imageanalytics#186]
##### Expected behavior
Image Embedding should appear as shown in the youtube tutorials

##### Actual behavior
It is missing in my orange version 3.23.1 version.

**Comment by ajdapretnar** [comment]
Please fill out the issue template. We cannot help you without specifying relevant information.

**Comment by PrimozGodec** [comment]
What is the version of Image Analytics you have installed? If it is not the newest have you tried to upgrade it?

**Comment by PrimozGodec** [comment]
I am closing this PR due to inactivity. If the issue reappears please feel free to reopen the PR.
