### ISSUE TITLE
Image Embedding: Image are skipped

### ISSUE THREAD

**Issue by IKetchup** [biolab/orange3-imageanalytics#192]
When I load my images (dataset of images of stain glasses) and I choose an Embedder other than SqueezeNet the widget return a warning saying my images are skiped

##### Image Analytics version
0.5.3

##### Orange version
3.27.1

##### Expected behavior
Return Embedding of the images

##### Actual behavior
Return nothing and print the warning "x images are skipped"

##### Steps to reproduce the behavior
Import images -> Image Embedding: choose an embedder other than squeezeNet

##### Additional info (worksheets, data, screenshots, ...)
Dataset of 24 jpg images of stain glasses

**Comment by PrimozGodec** [comment]
Thank you for submitting the issue. I cannot reproduce that on my computer and my set of images. Does it happen on any dataset of images you use or just on this particular dataset?

The other reason might be a proxy. Is your internet connection behind a proxy or a firewall.

**Comment by IKetchup** [comment]
This also happen with different dataset. When I change the image extension (pjp to png) images are skipped in the widget "Import Images". However with another data set of png images it's work fine.

Is there a reason (format, size, weight..) that would skip the image?

Internet connection seen to not be the problem

**Comment by PrimozGodec** [comment]
@IKetchup I think I have found the reason for the error. It was a bug which we already solved in https://github.com/biolab/orange3-imageanalytics/pull/189, but we forgot to make a release after. Sorry for causing you problems. 

Can you upgrade the version of the orange3-imageanalytics addon to 0.6.0 (you can upgrade in the addon dialog: options>add-ons)? Please let us know if it solves your issue.

In case you will have any further issues I am happy to help.

**Comment by IKetchup** [comment]
Its working well thanks
