### ISSUE TITLE
Image attributes lost?

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3-imageanalytics#202]
##### Image Analytics version

 v 0.6.0

##### Orange version

v 3.30.1

##### Expected behavior

Passing images to Image Grid widget should load images (?)

##### Actual behavior

'image name' attribute loses 'type=image'

![image](https://user-images.githubusercontent.com/17868615/134818857-7935ed50-7481-4b1b-81c2-bdec2bbdb4f4.png)

**Comment by ales-erjavec** [comment]
The error message is wrong/confusing. You have to select "image" from the *Image Filename Attribute* drop down and not "image name".
