### ISSUE TITLE
Info about remote server used to get embedding

### ISSUE THREAD

**Issue by jsmazapad** [biolab/orange3-imageanalytics#212]
Hi, I´m a student interested in the server used for getting features vectors from embedding models (api.garaza.io) to use in my Ending Master Work. I didn´t found any documentation on the net. Where can I find it?

Thanks in advance

**Comment by ajdapretnar** [comment]
Do you mean server documentation? This is our private server used exclusively for Orange functionalities. It doesn't and it won't come with any documentation.
If you are interested in Image Embedding documentation, it is here: https://orangedatamining.com/widget-catalog/image-analytics/imageembedding/
