### ISSUE TITLE
Image Viewer doesn't load from network on Qt 6

### ISSUE THREAD

**Issue by janezd** [biolab/orange3-imageanalytics#229]
`widget.owimageviewer.loader_qnam` fails in `request.setAttribute(QNetworkRequest.FollowRedirectsAttribute, True)` because QNetworkRequest::FollowRedirectsAttribute is removed in Qt 6 (https://doc.qt.io/qt-6/network-changes-qt6.html#redirect-policies).

##### Steps to reproduce the behavior

Run the preview.

**Comment by ales-erjavec** [comment]
I think this was already fixed in https://github.com/biolab/orange3-imageanalytics/pull/223
