### ISSUE TITLE
Import Images Widget Info Typo

### ISSUE THREAD

**Issue by foongminwong** [biolab/orange3-imageanalytics#239]
##### Image Analytics version

0.12.2

##### Orange version

3.36.2

##### Expected behavior
It should show `categories` instead of `categorys`.

##### Actual behavior
It shows `categorys` instead of `categories`.

##### Steps to reproduce the behavior
I imported an image-data folder with 3 labeled subfolders
![image](https://github.com/biolab/orange3-imageanalytics/assets/23441795/4bbf5c10-f590-4f27-bdbf-e5745a5783ba)

##### Additional info (worksheets, data, screenshots, ...)
As suggested by Orange3 https://github.com/biolab/orange3/issues/6753#issuecomment-1976468753, `from orangecanvas.utils.localization import pl` should be replaced by `from Orange.widgets.utils.localization import pl` in [owimageimport.py](https://github.com/biolab/orange3-imageanalytics/blob/master/orangecontrib/imageanalytics/widgets/owimageimport.py#L38 )

**Comment by janezd** [comment]
Thanks. This has now been fixed in https://github.com/biolab/orange3/pull/6758.
