### ISSUE TITLE
Image Embedding: crashes when nothing in dropdown

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3-imageanalytics#45]
##### Orange version
master

##### Image Analytics version
0.1.7

##### Expected behavior
Does not crash.

##### Actual behavior
![screenshot_20170609_152511](https://user-images.githubusercontent.com/22157215/26977417-194a88c4-4d28-11e7-8a77-bdb3511ea357.png)

##### Steps to reproduce the behavior
See a screenshot above.

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-imageanalytics/issues/290587305/

**Comment by bernardofn** [comment]
Today, I tried to install the widget Image Analytics, and it is not appearing in the left menu.

**Comment by inejc** [comment]
@bernardofn see https://github.com/biolab/orange3-imageanalytics/issues/42#issuecomment-306761945.
