### ISSUE TITLE
ImageEmbedding: Issue warning when images skipped

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-imageanalytics#51]
It would be nice (and useful) to receive a warning, when images are skipped for embedding. It could be already in the infobox, e.g.:
_Embedded: 23/30_
or
_7 images skipped_
or
a traditional warning.
Also since when is TIFF not supported? I am getting a silent ignore of tiff, but everything works on jpeg.

**Comment by inejc** [comment]
Opened a PR regarding the skipped images warning. TIFF works for me (tried 50 images with all embedders), perhaps a different issue?

**Comment by ajdapretnar** [comment]
Closed via #53.
