### ISSUE TITLE
Implement ImportImages as scripting

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-imageanalytics#57]
I'm trying to use Image Analytics in the scripting part and I've just realized one can only import images through GUI. Would it be possible to separate the function for reading images and constructing Orange.data.Table from the widget?

e.g.
from orangecontrib.imageanalytics.images_from_file import ImportImages
images = ImportImages("../path")

**Comment by jerneju** [comment]
Sure. Something like **Import Documents**, right?

**Comment by ajdapretnar** [comment]
Exactly.
