### ISSUE TITLE
ImageEmbedder - Memory Error

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3-imageanalytics#64]
**Orange version**
3.6.0

**Expected behavior**
Widget completes processing

**Actual behavior**
Widget gets to ~80% and fails due to a Memory Error

**Steps to reproduce the behavior**
Load a 'moderately sized' directory of images

**Additional info (worksheets, data, screenshots, ...)**
1830 images, 307MB total.

Computer is running:
Windows 10 Pro
Intel i7-6700K CPU @ 4GHz
64 GB RAM total (62 GB available during processing the images)

**Comment by kernc** [comment]
Can you provide a full backtrace (the error message that begins with `Traceback` and ends with `MemoryError` line).

**Comment by PrimozGodec** [comment]
I think it is solved in https://github.com/biolab/orange3-imageanalytics/pull/66. 
If it is not feel free to reopen the issue with more informations.
