### ISSUE TITLE
Got the error while trying to add-on "Image Analytics""

### ISSUE THREAD

**Issue by Pearapon** [biolab/orange3-imageanalytics#80]
##### Image Analytics version

Got the error while trying to add-on "Image Analytics"". I am using "Windows 10 pro" 64 bits. Orange is installed with "Orange 3.8" 

##### Steps to reproduce the behavior
This is error detail
Collecting Orange3-ImageAnalytics
  Using cached Orange3-ImageAnalytics-0.1.13.tar.gz
Requirement already satisfied: Orange3>=3.3.5 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: Pillow>=4.2.1 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: cachecontrol in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: hyper>=0.7.0 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3-ImageAnalytics)
Collecting lap==0.3.0 (from Orange3-ImageAnalytics)
  Using cached lap-0.3.0.tar.gz
Collecting lockfile (from Orange3-ImageAnalytics)
  Using cached lockfile-0.12.2-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.10.0 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: requests in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3-ImageAnalytics)
Requirement already satisfied: scipy>=0.16.1 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: setuptools>=36.3 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: pyqtgraph>=0.10.0 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: CommonMark>=0.5.5 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: serverfiles in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: docutils in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: bottleneck>=1.0.0 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: keyring in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: keyrings.alt in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: xlrd>=0.9.2 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: chardet>=3.0.2 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: scikit-learn>=0.18.1 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: joblib>=0.9.4 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: dill in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: AnyQt>=0.0.8 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: pip>=9.0 in c:\users\intel\appdata\local\orange\lib\site-packages (from Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: msgpack-python in c:\users\intel\appdata\local\orange\lib\site-packages (from cachecontrol->Orange3-ImageAnalytics)
Requirement already satisfied: hyperframe<4.0,>=3.2 in c:\users\intel\appdata\local\orange\lib\site-packages (from hyper>=0.7.0->Orange3-ImageAnalytics)
Requirement already satisfied: h2<3.0,>=2.4 in c:\users\intel\appdata\local\orange\lib\site-packages (from hyper>=0.7.0->Orange3-ImageAnalytics)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\intel\appdata\local\orange\lib\site-packages (from requests->Orange3-ImageAnalytics)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\intel\appdata\local\orange\lib\site-packages (from requests->Orange3-ImageAnalytics)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\intel\appdata\local\orange\lib\site-packages (from requests->Orange3-ImageAnalytics)
Requirement already satisfied: future in c:\users\intel\appdata\local\orange\lib\site-packages (from CommonMark>=0.5.5->Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: pywin32 in c:\users\intel\appdata\local\orange\lib\site-packages (from keyring->Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: six in c:\users\intel\appdata\local\orange\lib\site-packages (from keyrings.alt->Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: pyreadline>=1.7.1 in c:\users\intel\appdata\local\orange\lib\site-packages (from dill->Orange3>=3.3.5->Orange3-ImageAnalytics)
Requirement already satisfied: hpack<4,>=2.2 in c:\users\intel\appdata\local\orange\lib\site-packages (from h2<3.0,>=2.4->hyper>=0.7.0->Orange3-ImageAnalytics)
Building wheels for collected packages: Orange3-ImageAnalytics, lap
  Running setup.py bdist_wheel for Orange3-ImageAnalytics: started
  Running setup.py bdist_wheel for Orange3-ImageAnalytics: finished with status 'done'
  Running setup.py clean for Orange3-ImageAnalytics
  Running setup.py bdist_wheel for lap: started
  Running setup.py bdist_wheel for lap: finished with status 'error'
  Complete output from command C:\Users\Intel\AppData\Local\Orange\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Intel\\AppData\\Local\\Temp\\pip-build-hqim64i8\\lap\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Intel\AppData\Local\Temp\tmpm5mq108opip-wheel- --python-tag cp36:
  Partial import of lap during the build process.
  Generating cython files
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "lap._lapjv" sources
  building data_files sources
  build_src: building npy-pkg config files
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\lap
  copying lap\lapmod.py -> build\lib.win-amd64-3.6\lap
  copying lap\__init__.py -> build\lib.win-amd64-3.6\lap
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  Missing compiler_cxx fix for MSVCCompiler
  customize MSVCCompiler using build_ext
  building 'lap._lapjv' extension
  compiling C sources
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
  
  ----------------------------------------
  Failed building wheel for lap
  Running setup.py clean for lap
Failed to build Orange3-ImageAnalytics lap
Installing collected packages: lap, lockfile, Orange3-ImageAnalytics
  Running setup.py install for lap: started
    Running setup.py install for lap: finished with status 'error'
    Complete output from command C:\Users\Intel\AppData\Local\Orange\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Intel\\AppData\\Local\\Temp\\pip-build-hqim64i8\\lap\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Intel\AppData\Local\Temp\pip-3ncfmn_d-record\install-record.txt --single-version-externally-managed --compile:
    Partial import of lap during the build process.
    Generating cython files
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "lap._lapjv" sources
    building data_files sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\lap
    copying lap\lapmod.py -> build\lib.win-amd64-3.6\lap
    copying lap\__init__.py -> build\lib.win-amd64-3.6\lap
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext
    building 'lap._lapjv' extension
    compiling C sources
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
    
    ----------------------------------------
Command "C:\Users\Intel\AppData\Local\Orange\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Intel\\AppData\\Local\\Temp\\pip-build-hqim64i8\\lap\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Intel\AppData\Local\Temp\pip-3ncfmn_d-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Intel\AppData\Local\Temp\pip-build-hqim64i8\lap\

##### Additional info (worksheets, data, screenshots, ...)
![add-on_1](https://user-images.githubusercontent.com/27675996/34490276-f3eb0986-f011-11e7-8d82-6e753a6266ee.PNG)

**Comment by PrimozGodec** [comment]
It can be solved installing `Microsoft Visual C++` on your machine.

@janhartman is there any option to use the `lap` package without having `Microsoft Visual C++` installed or use any other package in the `ImageGrid` widget instead.

**Comment by ajdapretnar** [comment]
I think we should make _lap_ for now an optional dependency and have Win users missing Image Grid instead of not being able to install Image Analytics at all.
Also, could it be installed with conda?

**Comment by PrimozGodec** [comment]
@ajdapretnar I agree with you. We need to make it work as soon as possible. 
@janhartman Can you find the solution for that?

**Comment by janhartman** [comment]
The issue has been fixed in #84 -  I removed the problematic package.

**Comment by kernc** [comment]
xref: https://stackoverflow.com/questions/48109216/in-installing-orange-imageanalytics

**Comment by janhartman** [comment]
I apologize for all the trouble this has caused. I did not realize the `lap` package would be so problematic on Windows - the package's Appveyor builds run fine on Windows, and I have only tried installing it on Linux. I hope the situation is now resolved in #84.
