### ISSUE TITLE
Provide conda binaries

### ISSUE THREAD

**Issue by astaric** [biolab/orange3-imageanalytics#83]
Ref #80 

A conda package (on conda-forge) would allow windows users to use all the widgets. New recipes are added to the conda-forge by opening a pull request to the [staged recipes repository](https://github.com/conda-forge/staged-recipes/).

For inspiration, see existing conda recipes for other add-ons.
https://github.com/conda-forge/orange3-text-feedstock/blob/master/recipe/meta.yaml
https://github.com/conda-forge/orange3-timeseries-feedstock/blob/master/recipe/meta.yaml
https://github.com/conda-forge/orange3-network-feedstock/blob/master/recipe/meta.yaml
https://github.com/conda-forge/orange3-geo-feedstock/blob/master/recipe/meta.yaml

**Comment by PrimozGodec** [comment]
https://github.com/conda-forge/staged-recipes/pull/4737

**Comment by PrimozGodec** [comment]
Done, so closing this issue.
