### ISSUE TITLE
Image Grid: Colors don't correspond to the core Orange colors

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-imageanalytics#89]
##### Image Analytics version

0.1.15

##### Orange version

3.10.dev

##### Expected behavior
Colors in Image Grid (when selecting groups) and coloring in MDS correspond.

##### Actual behavior
Image Grid colors groups with 1 value off the official coloring in Orange.

##### Steps to reproduce the behavior
Select image groups in Image Grid, connect MDS and color by Group.

##### Additional info (worksheets, data, screenshots, ...)
Blue is nowhere to be found.

<img width="1653" alt="screen shot 2018-02-13 at 17 23 15" src="https://user-images.githubusercontent.com/12524972/36160963-d1e22ec2-10e2-11e8-85ff-15aee95b7237.png">

**Comment by PrimozGodec** [comment]
@janhartman can you check that?

**Comment by janhartman** [comment]
Weird - I used the same colors as Scatter Plot as I was instructed. I can check this weekend.

**Comment by ajdapretnar** [comment]
It could be just indexing?

**Comment by astaric** [comment]
@ajdapretnar, try doing multiple selection in scatterplot and show it in another scatter plot. It exhibits the same behavior

**Comment by astaric** [comment]
<img width="929" alt="screen shot 2018-02-14 at 15 36 04" src="https://user-images.githubusercontent.com/588601/36209734-de604a84-119c-11e8-87af-eab3a79d8741.png">

**Comment by ajdapretnar** [comment]
Fixed in #107.
